/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleServicesIndexRouteImport } from './routes/$locale.services.index'
import { Route as LocaleIndustriesIndexRouteImport } from './routes/$locale.industries.index'
import { Route as LocaleCaseStudiesIndexRouteImport } from './routes/$locale.case-studies.index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale.blog.index'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'
import { Route as LocaleLocationsSlugRouteImport } from './routes/$locale.locations.$slug'
import { Route as LocaleIndustriesSlugRouteImport } from './routes/$locale.industries.$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale.blog.$slug'
import { Route as LocaleServicesSlugIndexRouteImport } from './routes/$locale.services.$slug.index'
import { Route as LocaleServicesSlugSubRouteImport } from './routes/$locale.services.$slug.$sub'
import { Route as LocaleIndustriesSlugSubRouteImport } from './routes/$locale.industries.$slug.$sub'
import { Route as LocaleBlogCategorySlugRouteImport } from './routes/$locale.blog.category.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesIndexRoute = LocaleServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleIndustriesIndexRoute = LocaleIndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCaseStudiesIndexRoute = LocaleCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AdminPagesRoute,
} as any)
const LocaleLocationsSlugRoute = LocaleLocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleIndustriesSlugRoute = LocaleIndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesSlugIndexRoute = LocaleServicesSlugIndexRouteImport.update({
  id: '/services/$slug/',
  path: '/services/$slug/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesSlugSubRoute = LocaleServicesSlugSubRouteImport.update({
  id: '/services/$slug/$sub',
  path: '/services/$slug/$sub',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleIndustriesSlugSubRoute = LocaleIndustriesSlugSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => LocaleIndustriesSlugRoute,
} as any)
const LocaleBlogCategorySlugRoute = LocaleBlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/industries/$slug': typeof LocaleIndustriesSlugRouteWithChildren
  '/$locale/locations/$slug': typeof LocaleLocationsSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/case-studies/': typeof LocaleCaseStudiesIndexRoute
  '/$locale/industries/': typeof LocaleIndustriesIndexRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/industries/$slug/$sub': typeof LocaleIndustriesSlugSubRoute
  '/$locale/services/$slug/$sub': typeof LocaleServicesSlugSubRoute
  '/$locale/services/$slug/': typeof LocaleServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/industries/$slug': typeof LocaleIndustriesSlugRouteWithChildren
  '/$locale/locations/$slug': typeof LocaleLocationsSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/case-studies': typeof LocaleCaseStudiesIndexRoute
  '/$locale/industries': typeof LocaleIndustriesIndexRoute
  '/$locale/services': typeof LocaleServicesIndexRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/industries/$slug/$sub': typeof LocaleIndustriesSlugSubRoute
  '/$locale/services/$slug/$sub': typeof LocaleServicesSlugSubRoute
  '/$locale/services/$slug': typeof LocaleServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/industries/$slug': typeof LocaleIndustriesSlugRouteWithChildren
  '/$locale/locations/$slug': typeof LocaleLocationsSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/case-studies/': typeof LocaleCaseStudiesIndexRoute
  '/$locale/industries/': typeof LocaleIndustriesIndexRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
  '/$locale/blog/category/$slug': typeof LocaleBlogCategorySlugRoute
  '/$locale/industries/$slug/$sub': typeof LocaleIndustriesSlugSubRoute
  '/$locale/services/$slug/$sub': typeof LocaleServicesSlugSubRoute
  '/$locale/services/$slug/': typeof LocaleServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/about'
    | '/$locale/contact'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/$locale/'
    | '/admin/'
    | '/$locale/blog/$slug'
    | '/$locale/industries/$slug'
    | '/$locale/locations/$slug'
    | '/admin/pages/$pageId'
    | '/$locale/blog/'
    | '/$locale/case-studies/'
    | '/$locale/industries/'
    | '/$locale/services/'
    | '/$locale/blog/category/$slug'
    | '/$locale/industries/$slug/$sub'
    | '/$locale/services/$slug/$sub'
    | '/$locale/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/contact'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/$locale'
    | '/admin'
    | '/$locale/blog/$slug'
    | '/$locale/industries/$slug'
    | '/$locale/locations/$slug'
    | '/admin/pages/$pageId'
    | '/$locale/blog'
    | '/$locale/case-studies'
    | '/$locale/industries'
    | '/$locale/services'
    | '/$locale/blog/category/$slug'
    | '/$locale/industries/$slug/$sub'
    | '/$locale/services/$slug/$sub'
    | '/$locale/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/about'
    | '/$locale/contact'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/$locale/'
    | '/admin/'
    | '/$locale/blog/$slug'
    | '/$locale/industries/$slug'
    | '/$locale/locations/$slug'
    | '/admin/pages/$pageId'
    | '/$locale/blog/'
    | '/$locale/case-studies/'
    | '/$locale/industries/'
    | '/$locale/services/'
    | '/$locale/blog/category/$slug'
    | '/$locale/industries/$slug/$sub'
    | '/$locale/services/$slug/$sub'
    | '/$locale/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/': {
      id: '/$locale/services/'
      path: '/services'
      fullPath: '/$locale/services/'
      preLoaderRoute: typeof LocaleServicesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/industries/': {
      id: '/$locale/industries/'
      path: '/industries'
      fullPath: '/$locale/industries/'
      preLoaderRoute: typeof LocaleIndustriesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/case-studies/': {
      id: '/$locale/case-studies/'
      path: '/case-studies'
      fullPath: '/$locale/case-studies/'
      preLoaderRoute: typeof LocaleCaseStudiesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/$locale/locations/$slug': {
      id: '/$locale/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/$locale/locations/$slug'
      preLoaderRoute: typeof LocaleLocationsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/industries/$slug': {
      id: '/$locale/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/$locale/industries/$slug'
      preLoaderRoute: typeof LocaleIndustriesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/$slug/': {
      id: '/$locale/services/$slug/'
      path: '/services/$slug'
      fullPath: '/$locale/services/$slug/'
      preLoaderRoute: typeof LocaleServicesSlugIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/$slug/$sub': {
      id: '/$locale/services/$slug/$sub'
      path: '/services/$slug/$sub'
      fullPath: '/$locale/services/$slug/$sub'
      preLoaderRoute: typeof LocaleServicesSlugSubRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/industries/$slug/$sub': {
      id: '/$locale/industries/$slug/$sub'
      path: '/$sub'
      fullPath: '/$locale/industries/$slug/$sub'
      preLoaderRoute: typeof LocaleIndustriesSlugSubRouteImport
      parentRoute: typeof LocaleIndustriesSlugRoute
    }
    '/$locale/blog/category/$slug': {
      id: '/$locale/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/$locale/blog/category/$slug'
      preLoaderRoute: typeof LocaleBlogCategorySlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleIndustriesSlugRouteChildren {
  LocaleIndustriesSlugSubRoute: typeof LocaleIndustriesSlugSubRoute
}

const LocaleIndustriesSlugRouteChildren: LocaleIndustriesSlugRouteChildren = {
  LocaleIndustriesSlugSubRoute: LocaleIndustriesSlugSubRoute,
}

const LocaleIndustriesSlugRouteWithChildren =
  LocaleIndustriesSlugRoute._addFileChildren(LocaleIndustriesSlugRouteChildren)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleIndustriesSlugRoute: typeof LocaleIndustriesSlugRouteWithChildren
  LocaleLocationsSlugRoute: typeof LocaleLocationsSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleCaseStudiesIndexRoute: typeof LocaleCaseStudiesIndexRoute
  LocaleIndustriesIndexRoute: typeof LocaleIndustriesIndexRoute
  LocaleServicesIndexRoute: typeof LocaleServicesIndexRoute
  LocaleBlogCategorySlugRoute: typeof LocaleBlogCategorySlugRoute
  LocaleServicesSlugSubRoute: typeof LocaleServicesSlugSubRoute
  LocaleServicesSlugIndexRoute: typeof LocaleServicesSlugIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleIndustriesSlugRoute: LocaleIndustriesSlugRouteWithChildren,
  LocaleLocationsSlugRoute: LocaleLocationsSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleCaseStudiesIndexRoute: LocaleCaseStudiesIndexRoute,
  LocaleIndustriesIndexRoute: LocaleIndustriesIndexRoute,
  LocaleServicesIndexRoute: LocaleServicesIndexRoute,
  LocaleBlogCategorySlugRoute: LocaleBlogCategorySlugRoute,
  LocaleServicesSlugSubRoute: LocaleServicesSlugSubRoute,
  LocaleServicesSlugIndexRoute: LocaleServicesSlugIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminPagesRouteChildren {
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminFormsRoute: typeof AdminFormsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormsRoute: AdminFormsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
