/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}.contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}.about'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as Char123LocaleChar125ServicesIndexRouteImport } from './routes/{-$locale}.services.index'
import { Route as Char123LocaleChar125IndustriesIndexRouteImport } from './routes/{-$locale}.industries.index'
import { Route as Char123LocaleChar125CaseStudiesIndexRouteImport } from './routes/{-$locale}.case-studies.index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}.blog.index'
import { Route as Char123LocaleChar125LocationsSlugRouteImport } from './routes/{-$locale}.locations.$slug'
import { Route as Char123LocaleChar125IndustriesSlugRouteImport } from './routes/{-$locale}.industries.$slug'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}.blog.$slug'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'
import { Route as Char123LocaleChar125ServicesSlugIndexRouteImport } from './routes/{-$locale}.services.$slug.index'
import { Route as Char123LocaleChar125ServicesSlugSubRouteImport } from './routes/{-$locale}.services.$slug.$sub'
import { Route as Char123LocaleChar125IndustriesSlugSubRouteImport } from './routes/{-$locale}.industries.$slug.$sub'
import { Route as Char123LocaleChar125BlogCategorySlugRouteImport } from './routes/{-$locale}.blog.category.$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const Char123LocaleChar125ServicesIndexRoute =
  Char123LocaleChar125ServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125IndustriesIndexRoute =
  Char123LocaleChar125IndustriesIndexRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CaseStudiesIndexRoute =
  Char123LocaleChar125CaseStudiesIndexRouteImport.update({
    id: '/case-studies/',
    path: '/case-studies/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LocationsSlugRoute =
  Char123LocaleChar125LocationsSlugRouteImport.update({
    id: '/locations/$slug',
    path: '/locations/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125IndustriesSlugRoute =
  Char123LocaleChar125IndustriesSlugRouteImport.update({
    id: '/industries/$slug',
    path: '/industries/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AdminPagesRoute,
} as any)
const Char123LocaleChar125ServicesSlugIndexRoute =
  Char123LocaleChar125ServicesSlugIndexRouteImport.update({
    id: '/services/$slug/',
    path: '/services/$slug/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesSlugSubRoute =
  Char123LocaleChar125ServicesSlugSubRouteImport.update({
    id: '/services/$slug/$sub',
    path: '/services/$slug/$sub',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125IndustriesSlugSubRoute =
  Char123LocaleChar125IndustriesSlugSubRouteImport.update({
    id: '/$sub',
    path: '/$sub',
    getParentRoute: () => Char123LocaleChar125IndustriesSlugRoute,
  } as any)
const Char123LocaleChar125BlogCategorySlugRoute =
  Char123LocaleChar125BlogCategorySlugRouteImport.update({
    id: '/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/industries/$slug': typeof Char123LocaleChar125IndustriesSlugRouteWithChildren
  '/{-$locale}/locations/$slug': typeof Char123LocaleChar125LocationsSlugRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies/': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/industries/': typeof Char123LocaleChar125IndustriesIndexRoute
  '/{-$locale}/services/': typeof Char123LocaleChar125ServicesIndexRoute
  '/{-$locale}/blog/category/$slug': typeof Char123LocaleChar125BlogCategorySlugRoute
  '/{-$locale}/industries/$slug/$sub': typeof Char123LocaleChar125IndustriesSlugSubRoute
  '/{-$locale}/services/$slug/$sub': typeof Char123LocaleChar125ServicesSlugSubRoute
  '/{-$locale}/services/$slug/': typeof Char123LocaleChar125ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/admin': typeof AdminIndexRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/industries/$slug': typeof Char123LocaleChar125IndustriesSlugRouteWithChildren
  '/{-$locale}/locations/$slug': typeof Char123LocaleChar125LocationsSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/industries': typeof Char123LocaleChar125IndustriesIndexRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesIndexRoute
  '/{-$locale}/blog/category/$slug': typeof Char123LocaleChar125BlogCategorySlugRoute
  '/{-$locale}/industries/$slug/$sub': typeof Char123LocaleChar125IndustriesSlugSubRoute
  '/{-$locale}/services/$slug/$sub': typeof Char123LocaleChar125ServicesSlugSubRoute
  '/{-$locale}/services/$slug': typeof Char123LocaleChar125ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/admin/forms': typeof AdminFormsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/industries/$slug': typeof Char123LocaleChar125IndustriesSlugRouteWithChildren
  '/{-$locale}/locations/$slug': typeof Char123LocaleChar125LocationsSlugRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies/': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/industries/': typeof Char123LocaleChar125IndustriesIndexRoute
  '/{-$locale}/services/': typeof Char123LocaleChar125ServicesIndexRoute
  '/{-$locale}/blog/category/$slug': typeof Char123LocaleChar125BlogCategorySlugRoute
  '/{-$locale}/industries/$slug/$sub': typeof Char123LocaleChar125IndustriesSlugSubRoute
  '/{-$locale}/services/$slug/$sub': typeof Char123LocaleChar125ServicesSlugSubRoute
  '/{-$locale}/services/$slug/': typeof Char123LocaleChar125ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/{-$locale}'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/admin/'
    | '/{-$locale}/'
    | '/admin/pages/$pageId'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/industries/$slug'
    | '/{-$locale}/locations/$slug'
    | '/{-$locale}/blog/'
    | '/{-$locale}/case-studies/'
    | '/{-$locale}/industries/'
    | '/{-$locale}/services/'
    | '/{-$locale}/blog/category/$slug'
    | '/{-$locale}/industries/$slug/$sub'
    | '/{-$locale}/services/$slug/$sub'
    | '/{-$locale}/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/admin'
    | '/{-$locale}'
    | '/admin/pages/$pageId'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/industries/$slug'
    | '/{-$locale}/locations/$slug'
    | '/{-$locale}/blog'
    | '/{-$locale}/case-studies'
    | '/{-$locale}/industries'
    | '/{-$locale}/services'
    | '/{-$locale}/blog/category/$slug'
    | '/{-$locale}/industries/$slug/$sub'
    | '/{-$locale}/services/$slug/$sub'
    | '/{-$locale}/services/$slug'
  id:
    | '__root__'
    | '/admin'
    | '/{-$locale}'
    | '/admin/forms'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/users'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/admin/'
    | '/{-$locale}/'
    | '/admin/pages/$pageId'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/industries/$slug'
    | '/{-$locale}/locations/$slug'
    | '/{-$locale}/blog/'
    | '/{-$locale}/case-studies/'
    | '/{-$locale}/industries/'
    | '/{-$locale}/services/'
    | '/{-$locale}/blog/category/$slug'
    | '/{-$locale}/industries/$slug/$sub'
    | '/{-$locale}/services/$slug/$sub'
    | '/{-$locale}/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/{-$locale}/services/': {
      id: '/{-$locale}/services/'
      path: '/services'
      fullPath: '/{-$locale}/services/'
      preLoaderRoute: typeof Char123LocaleChar125ServicesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/industries/': {
      id: '/{-$locale}/industries/'
      path: '/industries'
      fullPath: '/{-$locale}/industries/'
      preLoaderRoute: typeof Char123LocaleChar125IndustriesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/case-studies/': {
      id: '/{-$locale}/case-studies/'
      path: '/case-studies'
      fullPath: '/{-$locale}/case-studies/'
      preLoaderRoute: typeof Char123LocaleChar125CaseStudiesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/locations/$slug': {
      id: '/{-$locale}/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/{-$locale}/locations/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LocationsSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/industries/$slug': {
      id: '/{-$locale}/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/{-$locale}/industries/$slug'
      preLoaderRoute: typeof Char123LocaleChar125IndustriesSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/{-$locale}/services/$slug/': {
      id: '/{-$locale}/services/$slug/'
      path: '/services/$slug'
      fullPath: '/{-$locale}/services/$slug/'
      preLoaderRoute: typeof Char123LocaleChar125ServicesSlugIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/$slug/$sub': {
      id: '/{-$locale}/services/$slug/$sub'
      path: '/services/$slug/$sub'
      fullPath: '/{-$locale}/services/$slug/$sub'
      preLoaderRoute: typeof Char123LocaleChar125ServicesSlugSubRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/industries/$slug/$sub': {
      id: '/{-$locale}/industries/$slug/$sub'
      path: '/$sub'
      fullPath: '/{-$locale}/industries/$slug/$sub'
      preLoaderRoute: typeof Char123LocaleChar125IndustriesSlugSubRouteImport
      parentRoute: typeof Char123LocaleChar125IndustriesSlugRoute
    }
    '/{-$locale}/blog/category/$slug': {
      id: '/{-$locale}/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/{-$locale}/blog/category/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogCategorySlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface AdminPagesRouteChildren {
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminFormsRoute: typeof AdminFormsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormsRoute: AdminFormsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface Char123LocaleChar125IndustriesSlugRouteChildren {
  Char123LocaleChar125IndustriesSlugSubRoute: typeof Char123LocaleChar125IndustriesSlugSubRoute
}

const Char123LocaleChar125IndustriesSlugRouteChildren: Char123LocaleChar125IndustriesSlugRouteChildren =
  {
    Char123LocaleChar125IndustriesSlugSubRoute:
      Char123LocaleChar125IndustriesSlugSubRoute,
  }

const Char123LocaleChar125IndustriesSlugRouteWithChildren =
  Char123LocaleChar125IndustriesSlugRoute._addFileChildren(
    Char123LocaleChar125IndustriesSlugRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125IndustriesSlugRoute: typeof Char123LocaleChar125IndustriesSlugRouteWithChildren
  Char123LocaleChar125LocationsSlugRoute: typeof Char123LocaleChar125LocationsSlugRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
  Char123LocaleChar125CaseStudiesIndexRoute: typeof Char123LocaleChar125CaseStudiesIndexRoute
  Char123LocaleChar125IndustriesIndexRoute: typeof Char123LocaleChar125IndustriesIndexRoute
  Char123LocaleChar125ServicesIndexRoute: typeof Char123LocaleChar125ServicesIndexRoute
  Char123LocaleChar125BlogCategorySlugRoute: typeof Char123LocaleChar125BlogCategorySlugRoute
  Char123LocaleChar125ServicesSlugSubRoute: typeof Char123LocaleChar125ServicesSlugSubRoute
  Char123LocaleChar125ServicesSlugIndexRoute: typeof Char123LocaleChar125ServicesSlugIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125IndustriesSlugRoute:
    Char123LocaleChar125IndustriesSlugRouteWithChildren,
  Char123LocaleChar125LocationsSlugRoute:
    Char123LocaleChar125LocationsSlugRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
  Char123LocaleChar125CaseStudiesIndexRoute:
    Char123LocaleChar125CaseStudiesIndexRoute,
  Char123LocaleChar125IndustriesIndexRoute:
    Char123LocaleChar125IndustriesIndexRoute,
  Char123LocaleChar125ServicesIndexRoute:
    Char123LocaleChar125ServicesIndexRoute,
  Char123LocaleChar125BlogCategorySlugRoute:
    Char123LocaleChar125BlogCategorySlugRoute,
  Char123LocaleChar125ServicesSlugSubRoute:
    Char123LocaleChar125ServicesSlugSubRoute,
  Char123LocaleChar125ServicesSlugIndexRoute:
    Char123LocaleChar125ServicesSlugIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
